### ISSUE TITLE
Type NavigateService is already registered

### ISSUE THREAD

**Issue by Smilefish2** [handoing/flutter_page_router#1]
**run example error:**
```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                            4.9s
Syncing files to device iPhone Xʀ...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp(dirty):
flutter: Type NavigateService is already registered
flutter: 'package:get_it/get_it.dart':
flutter: Failed assertion: line 53 pos 12: 'allowReassignment || !_factories.containsKey(T)'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      GetIt.registerSingleton (package:get_it/get_it.dart:53:12)
flutter: #3      new PageRouterNav (package:flutter_page_router/page_router_nav.dart:10:11)
flutter: #4      new FlutterPageRouter (package:flutter_page_router/flutter_page_router.dart:21:31)
flutter: #5      routerInit (package:example/router/index.dart:51:30)
flutter: #6      MyApp.build (package:example/main.dart:12:32)
flutter: #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974:28)
flutter: #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
flutter: #17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by handoing** [comment]
IOS is not currently adapted, and subsequent versions will be updated

**Comment by Smilefish2** [comment]
Thanks.

**Comment by HugoHeneault** [comment]
Any update on iOS support? :-)

It would be cool to warn about it on the readme so iOS devs know it's not ready yet.

**Comment by HugoHeneault** [comment]
I have the same issue on android 😢 

This should be reopened I think :) 

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyAppWithProviders(dirty, dependencies: [EasyLocalizationProvider]):
Type NavigateService is already registered
'package:get_it/get_it.dart':
Failed assertion: line 93 pos 12: 'allowReassignment || !_factories.containsKey(T)'

The relevant error-causing widget was: 
  MyAppWithProviders file:///Users/hugo/dev/app/lib/main.dart:43:55
When the exception was thrown, this was the stack: 
#2      GetIt._register (package:get_it/get_it.dart:93:12)
#3      GetIt.registerSingleton (package:get_it/get_it.dart:77:5)
#4      new PageRouterNav (package:flutter_page_router/page_router_nav.dart:10:11)
#5      new FlutterPageRouter (package:flutter_page_router/flutter_page_router.dart:21:31)
#6      routerInit (package:app/ui/router.dart:100:30)
```
